---
title: "Explanatory variables maps"
output:
  html_document:
    toc: true
    toc_float: true
  word_document: default
  pdf_document:
    toc: true
editor_options: 
  markdown: 
    wrap: 72
---

```{r load packages, include=FALSE}
library(sf)
library(ggplot2)
library(dplyr)
library(classInt)
library(ggspatial)
library(patchwork)
```

```{r setup, include=FALSE}
# Exploratory notebook. This file lives in exploratory/; root.dir is set to the project root.
knitr::opts_knit$set(root.dir = "..")
```

```{r read data, include=FALSE}
liv_outline <- st_read("../Input_Data/Liverpool Metropolitan Boundary/liverpool_metropolitan_dissolved.gpkg")
dens_grid_geom <- st_read("../R Output/grid_full.gpkg")
```

```{r, include=FALSE}
# Data preparation
data <- dens_grid_geom %>% filter(builtup2011 == 1) %>% 
  mutate(oac_constrained = as.numeric(ifelse(SPRGRP == "7",1,0)),
         oac_cosmopolitan = as.numeric(ifelse(SPRGRP == "2",1,0)),
         oac_ethnicentral = as.numeric(ifelse(SPRGRP == "3",1,0)),
         oac_hardpressed = as.numeric(ifelse(SPRGRP == "8",1,0)),
         oac_suburban = as.numeric(ifelse(SPRGRP == "6",1,0))) %>% 
  select(amenity_count:deprivation, p_pre1919:oac_suburban) %>% 
  select(-m_to_park, -nb11_MDcount, -LSOA11CD, -Rank) %>% 
    mutate(min_to_livmain = if_else(min_to_livmain>50, 50, min_to_livmain)) 

names(data)
```

```{r, include=FALSE}
# Function for maps numeric using jenks/fisher
compute_fisher <- function(dataset, var) {
  
x  <- dplyr::pull(dataset, {{ var }})   # <<— correct column extraction
  
jenks <- classIntervals(x, n = 5, style = "fisher")

labels <- paste0(
  round(jenks$brks[-length(jenks$brks)], 0), "–", 
  round(jenks$brks[-1], 0), unit
)

dataset$jenks_group <- cut(
  x,
  breaks = jenks$brks,
  include.lowest = TRUE,
  labels = labels
)

dataset_new <- dataset

dataset_new
}
```

# Maps explanatory variables
### Distance to train stations

```{r, echo=FALSE, warning=FALSE}
var_name <- "Distance to train stations \n(Euclidian distance in meter)"
unit <- " m"

dataset_new <- compute_fisher(data, m_to_train)

plot_m_to_train <- 
ggplot(dataset_new) +
  geom_sf(aes(fill = jenks_group), color = NA) +
  scale_fill_viridis_d(option = "plasma", 
                       direction = 1, 
                       name = var_name) +
  theme_minimal()+
  geom_sf(data = liv_outline, fill = NA, color = "grey", size = 0.1) +
    theme(
    axis.text = element_blank(),    # remove numbers
    axis.ticks = element_blank(),   # remove tick marks
    axis.title = element_blank()    # remove axis titles
  ) 

plot_m_to_train

# ggsave(paste0("../R Export/plot_", var_name, ".jpg"),
#        plot = plot_m_to_train, device = "jpg")
```

### Minutes to Liverpool center

```{r, echo=FALSE, warning=FALSE}
var_name <- "Distance to Liverpool center \n(Driving time by car)"
unit <- " min"

dataset_new <- compute_fisher(data, min_to_livmain)

plot_min_to_livmain <- 
ggplot(dataset_new) +
  geom_sf(aes(fill = jenks_group), color = NA) +
  scale_fill_viridis_d(option = "plasma", 
                       direction = 1, 
                       name = var_name) +
  theme_minimal()+
  geom_sf(data = liv_outline, fill = NA, color = "grey", size = 0.1) +
    theme(
    axis.text = element_blank(),    # remove numbers
    axis.ticks = element_blank(),   # remove tick marks
    axis.title = element_blank()    # remove axis titles
  )

plot_min_to_livmain

# ggsave(paste0("../R Export/plot_", var_name, ".jpg"),
#        plot = plot_min_to_livmain, device = "jpg")
```


### Amenity count

```{r, echo=FALSE, warning=FALSE}
var_name <- "Amenity count"
unit <- " "

dataset_new <- compute_fisher(data, amenity_count)

plot_amenity_count <- 
ggplot(dataset_new) +
  geom_sf(aes(fill = jenks_group), color = NA) +
  scale_fill_viridis_d(option = "viridis", 
                       direction = -1, 
                       name = var_name) +
  theme_minimal()+
  geom_sf(data = liv_outline, fill = NA, color = "grey", size = 0.1) +
    theme(
    axis.text = element_blank(),    # remove numbers
    axis.ticks = element_blank(),   # remove tick marks
    axis.title = element_blank()    # remove axis titles
  ) 

plot_amenity_count

# ggsave(paste0("../R Export/plot_", var_name, ".jpg"),
#        plot = plot_amenity_count, device = "jpg")
```

### No. low density neighbors

```{r, echo=FALSE, warning=FALSE}
var_name <- "Number of low density \ncells in neighbourhood"
unit <- " "

dataset_new <- compute_fisher(data, nb11_LDcount)

plot_nb11_LDcount <- 
ggplot(dataset_new) +
  geom_sf(aes(fill = jenks_group), color = NA) +
  scale_fill_viridis_d(option = "viridis", 
                       direction = -1, 
                       name = var_name) +
  theme_minimal()+
  geom_sf(data = liv_outline, fill = NA, color = "grey", size = 0.1) +
    theme(
    axis.text = element_blank(),    # remove numbers
    axis.ticks = element_blank(),   # remove tick marks
    axis.title = element_blank()    # remove axis titles
  )

plot_nb11_LDcount

# ggsave(paste0("../R Export/plot_", var_name, ".jpg"),
#        plot = plot_nb11_LDcount, device = "jpg")
```

### No. high density neighbors

```{r, echo=FALSE, warning=FALSE}
var_name <- "Number of high density \ncells in neighbourhood"
unit <- " "

dataset_new <- compute_fisher(data, nb11_HDcount)

plot_nb11_HDcount <- 
ggplot(dataset_new) +
  geom_sf(aes(fill = jenks_group), color = NA) +
  scale_fill_viridis_d(option = "viridis", 
                       direction = -1, 
                       name = var_name) +
  theme_minimal()+
  geom_sf(data = liv_outline, fill = NA, color = "grey", size = 0.1) +
    theme(
    axis.text = element_blank(),    # remove numbers
    axis.ticks = element_blank(),   # remove tick marks
    axis.title = element_blank()    # remove axis titles
  ) 

plot_nb11_HDcount

# ggsave(paste0("../R Export/plot_", var_name, ".jpg"),
#        plot = plot_nb11_HDcount, device = "jpg")
```

### No. NB count

```{r, echo=FALSE, warning=FALSE}
var_name <- "Number of unbuilt cells \nin neighbourhood"
unit <- " "

dataset_new <- compute_fisher(data, nb11_NBcount)

plot_nb11_NBcount <- 
ggplot(dataset_new) +
  geom_sf(aes(fill = jenks_group), color = NA) +
  scale_fill_viridis_d(option = "viridis", 
                       direction = -1, 
                       name = var_name) +
  theme_minimal()+
  geom_sf(data = liv_outline, fill = NA, color = "grey", size = 0.1) +
    theme(
    axis.text = element_blank(),    # remove numbers
    axis.ticks = element_blank(),   # remove tick marks
    axis.title = element_blank()    # remove axis titles
  )

plot_nb11_NBcount

# ggsave(paste0("../R Export/plot_", var_name, ".jpg"),
#        plot = plot_nb11_NBcount, device = "jpg")
```

### Deprivation decile

```{r, echo=FALSE, warning=FALSE}
var_name <- "Deprivation decile"
unit <- " "

dataset_new <- compute_fisher(data, deprivation)

plot_deprivation <- 
ggplot(dataset_new) +
  geom_sf(aes(fill = jenks_group), color = NA) +
  scale_fill_viridis_d(option = "magma", 
                       direction = 1, 
                       name = var_name) +
  theme_minimal()+
  geom_sf(data = liv_outline, fill = NA, color = "grey", size = 0.1) +
    theme(
    axis.text = element_blank(),    # remove numbers
    axis.ticks = element_blank(),   # remove tick marks
    axis.title = element_blank()    # remove axis titles
  ) 

plot_deprivation

# ggsave(paste0("../R Export/plot_", var_name, ".jpg"),
#        plot = plot_deprivation, device = "jpg")
```


### SFH dominant

```{r, echo=FALSE, warning=FALSE}
var_name <- "Single-family housing \ndominant"
unit <- " %"

plot_sfh_share <- 
data %>% 
  ggplot()+
  geom_sf(aes(fill = sfh_share), color = NA)+
  scale_fill_viridis_c(option = "plasma", direction = -1, 
                       name = var_name  ) +     # use -1 to reverse
  theme_minimal()+
  geom_sf(data = liv_outline, fill = NA, color = "grey", size = 0.1) +
    theme(
    axis.text = element_blank(),    # remove numbers
    axis.ticks = element_blank(),   # remove tick marks
    axis.title = element_blank()    # remove axis titles
  ) 

plot_sfh_share

# ggsave(paste0("../R Export/plot_", var_name, ".jpg"),
#        plot = plot_sfh_share, device = "jpg")
```

### Perc. buildings pre 1919

```{r, echo=FALSE, warning=FALSE}
var_name <- "Share of buildings with \nconstruction year pre 1919"
unit <- " %"

plot_p_pre1919 <- 
data %>% 
  ggplot()+
  geom_sf(aes(fill = p_pre1919), color = NA)+
  scale_fill_viridis_c(option = "plasma", direction = -1, 
                       name = var_name  ) +     # use -1 to reverse
  theme_minimal()+
  geom_sf(data = liv_outline, fill = NA, color = "grey", size = 0.1) +
    theme(
    axis.text = element_blank(),    # remove numbers
    axis.ticks = element_blank(),   # remove tick marks
    axis.title = element_blank()    # remove axis titles
  ) 

plot_p_pre1919

# ggsave(paste0("../R Export/plot_", var_name, ".jpg"),
#        plot = plot_p_pre1919, device = "jpg")
```

### dens_group11

```{r, echo=FALSE, warning=FALSE}
var_name <- "dens_group11"
unit <- " "

plot_dens_group11 <- 
data %>% 
  ggplot()+
  geom_sf(aes(fill = dens_group11), color = NA)+
  scale_fill_manual(
      values = c(
      "NB" = "grey80",
      "LD" = "#99d594",  # light yellow-green (viridis-like)
      "MD" = "#ffffbf",  # medium green
      "HD" = "#fc8d59"),   # dark teal
  breaks = c("NB", "LD", "MD", "HD"),
  name = var_name
) +
    theme_minimal()+
  geom_sf(data = liv_outline, fill = NA, color = "grey", size = 0.1) +
    theme(
    axis.text = element_blank(),    # remove numbers
    axis.ticks = element_blank(),   # remove tick marks
    axis.title = element_blank()    # remove axis titles
  ) 

plot_dens_group11

# ggsave(paste0("../R Export/plot_", var_name, ".jpg"),
#        plot = plot_dens_group11, device = "jpg")
```

### oac_constrained

```{r, echo=FALSE, warning=FALSE}
var_name <- "OAC Constrained"

plot_oac_constrained <- 
data %>% 
  mutate(oac_constrained = as.factor(oac_constrained)) %>% 
  ggplot()+
  geom_sf(aes(fill = oac_constrained), color = NA)+
  scale_fill_manual(
    values = c("0" = "grey80", "1" = "#1f78b4"),  # pick any colors
    name = var_name
  ) +
    theme_minimal()+
  geom_sf(data = liv_outline, fill = NA, color = "grey", size = 0.1) +
    theme(
    axis.text = element_blank(),    # remove numbers
    axis.ticks = element_blank(),   # remove tick marks
    axis.title = element_blank()    # remove axis titles
  ) 

plot_oac_constrained

# ggsave(paste0("../R Export/plot_", var_name, ".jpg"),
#        plot = plot_oac_constrained, device = "jpg")
```

### oac_cosmopolitan

```{r, echo=FALSE, warning=FALSE}
var_name <- "OAC Cosmopolitan"

plot_oac_cosmopolitan <- 
data %>% 
  mutate(oac_cosmopolitan = as.factor(oac_cosmopolitan)) %>% 
  ggplot()+
  geom_sf(aes(fill = oac_cosmopolitan), color = NA)+
  scale_fill_manual(
    values = c("0" = "grey80", "1" = "#1f78b4"),  # pick any colors
    name = var_name
  ) +
    theme_minimal()+
  geom_sf(data = liv_outline, fill = NA, color = "grey", size = 0.1) +
    theme(
    axis.text = element_blank(),    # remove numbers
    axis.ticks = element_blank(),   # remove tick marks
    axis.title = element_blank()    # remove axis titles
  ) 

plot_oac_cosmopolitan

# ggsave(paste0("../R Export/plot_", var_name, ".jpg"),
#        plot = plot_oac_cosmopolitan, device = "jpg")
```

### oac_ethnicentral

```{r, echo=FALSE, warning=FALSE}
var_name <- "OAC Ethnicentral"

plot_oac_ethnicentral <- 
data %>% 
  mutate(oac_ethnicentral = as.factor(oac_ethnicentral)) %>% 
  ggplot()+
  geom_sf(aes(fill = oac_ethnicentral), color = NA)+
  scale_fill_manual(
    values = c("0" = "grey80", "1" = "#1f78b4"),  # pick any colors
    name = var_name
  ) +
    theme_minimal()+
  geom_sf(data = liv_outline, fill = NA, color = "grey", size = 0.1) +
    theme(
    axis.text = element_blank(),    # remove numbers
    axis.ticks = element_blank(),   # remove tick marks
    axis.title = element_blank()    # remove axis titles
  ) 

plot_oac_ethnicentral

# ggsave(paste0("../R Export/plot_", var_name, ".jpg"),
#        plot = plot_oac_ethnicentral, device = "jpg")
```


### oac_hardpressed

```{r, echo=FALSE, warning=FALSE}
var_name <- "OAC Hardpressed"

plot_oac_hardpressed <- 
data %>% 
  mutate(oac_hardpressed = as.factor(oac_hardpressed)) %>% 
  ggplot()+
  geom_sf(aes(fill = oac_hardpressed), color = NA)+
  scale_fill_manual(
    values = c("0" = "grey80", "1" = "#1f78b4"),  # pick any colors
    name = var_name
  ) +
    theme_minimal()+
  geom_sf(data = liv_outline, fill = NA, color = "grey", size = 0.1) +
    theme(
    axis.text = element_blank(),    # remove numbers
    axis.ticks = element_blank(),   # remove tick marks
    axis.title = element_blank()    # remove axis titles
  ) 

plot_oac_hardpressed

# ggsave(paste0("../R Export/plot_", var_name, ".jpg"),
#        plot = plot_oac_hardpressed, device = "jpg")
```

### oac_suburban

```{r, echo=FALSE, warning=FALSE}
var_name <- "OAC Suburban"

plot_oac_suburban <- 
data %>% 
  mutate(oac_suburban = as.factor(oac_suburban)) %>% 
  ggplot()+
  geom_sf(aes(fill = oac_suburban), color = NA)+
  scale_fill_manual(
    values = c("0" = "grey80", "1" = "#1f78b4"),  # pick any colors
    name = var_name
  ) +
    theme_minimal()+
  geom_sf(data = liv_outline, fill = NA, color = "grey", size = 0.1) +
    theme(
    axis.text = element_blank(),    # remove numbers
    axis.ticks = element_blank(),   # remove tick marks
    axis.title = element_blank()    # remove axis titles
  ) 
  # annotation_scale(
  #   style = "ticks",
  #   location = "br",      # bottom left
  # )

plot_oac_suburban

# ggsave(paste0("../R Export/plot_", var_name, ".jpg"),
#        plot = plot_oac_suburban, device = "jpg")
```

## Put all maps together

```{r}
all_maps_01 <- wrap_plots(
  plot_amenity_count, plot_nb11_NBcount,
  plot_min_to_livmain, plot_nb11_LDcount,
  plot_m_to_train, plot_nb11_HDcount,
  plot_deprivation, plot_p_pre1919, 
  ncol = 2,
  nrow = 4
)&
theme(
  legend.title = element_text(size = 6),
  legend.text  = element_text(size = 5),
  legend.key.height = unit(2, "mm"),
  legend.key.width  = unit(2, "mm")
)

all_maps_02 <- wrap_plots(
  plot_sfh_share, plot_dens_group11,
  plot_oac_constrained, plot_oac_cosmopolitan,
  plot_oac_ethnicentral, plot_oac_hardpressed, 
  plot_oac_suburban,
  ncol = 2,
  nrow = 4
)&
theme(
  legend.title = element_text(size = 6),
  legend.text  = element_text(size = 5),
  legend.key.height = unit(2, "mm"),
  legend.key.width  = unit(2, "mm")
)

ggsave(
  "../R Export/explanatory_maps_01.jpg",
  all_maps_01,
  width = 180,
  # height = 240,
  units = "mm"
)

ggsave(
  "../R Export/explanatory_maps_02.jpg",
  all_maps_02,
  width = 180,
  # height = 240,
  units = "mm"
)
```


